### ISSUE TITLE
IERS Table doesn't include recent JDs

### ISSUE THREAD

**Issue by aelanman** [HERA-Team/pyuvdata#100]
When I attempt load a hera19 MIRIAD file into pyuvdata, it breaks on set_lsts_from_time_array() with the following error:
astropy.utils.iers.iers.IERSRangeError: (some) times are outside of range covered by IERS table.

Matt Kolopanis says he's had the same issue, and resolved it by updating to astropy 1.2. Might it be possible to update the IERS table on the fly when this error comes up?

**Comment by bhazelton** [comment]
My understanding was that with astropy >= 1.2 it should do the download on the fly. We should investigate why that's not happening.

**Comment by aelanman** [comment]
I should note that I had astropy 1.1 installed when this error came up. It worked fine when I upgraded to 1.2. I don't know if it's updating at runtime or was just updated because I installed 1.2... if it is updating as you say, then there is no issue.

**Comment by bhazelton** [comment]
Ok, I'll close it for now, but please re-open if you see a problem with astropy >= 1.2

**Comment by mkolopanis** [comment]
I think the real "issue" is that astropy >1.2 is "required" for installation but the requirement is not enforced.

**Comment by bhazelton** [comment]
If there's a better way to do it than the way it's done, please fix it!
