### ISSUE TITLE
How to handle omnical model visibilities, chi-square's, and xtalk outputs 

### ISSUE THREAD

**Issue by zakiali** [HERA-Team/pyuvdata#101]
How should we handle the model visibilities, chi-squares, and crosstalk outputs from omnical in terms of pyuvdata calibrations objects? Should these be truly optional parameters in UVCal objects or would a subclass of the UVCal object be better? 
It also gets a little tricky since the model visibilities are only output for each group of redundant baseline, not all, and crosstalk outputs are for every baseline, but only a single integration. 
Thoughts?

**Comment by bhazelton** [comment]
We should put the chi-squares into the cal quality_array. The model visibilities and crosstalk outputs (which look like visibilities) should be put into a uvdata object and saved to a file that way.

**Comment by bhazelton** [comment]
Has this issue been effectively addressed in the cal branch? @zakiali
