### ISSUE TITLE
aipy startup fail on mac

### ISSUE THREAD

**Issue by rbw42** [HERA-Team/pyuvdata#102]
Hi Folks,

As requested by Danny, here's what happens when I try to use aipy on my mac.
(rwayth$ uname -a
Darwin airbears2-10-142-31-176.airbears2.1918.berkeley.edu 15.6.0 Darwin Kernel Version 15.6.0: Thu Sep  1 15:01:16 PDT 2016; root:xnu-3248.60.11~2/RELEASE_X86_64 x86_64)
OSX 10.11.6

rwayth$ python
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import aipy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/aipy-2.1.0-py2.7-macosx-10.11-intel.egg/aipy/__init__.py", line 13, in <module>
    import phs, const, coord, deconv
  File "/Library/Python/2.7/site-packages/aipy-2.1.0-py2.7-macosx-10.11-intel.egg/aipy/phs.py", line 6, in <module>
    from miriad import ij2bl, bl2ij
  File "/Library/Python/2.7/site-packages/aipy-2.1.0-py2.7-macosx-10.11-intel.egg/aipy/miriad.py", line 9, in <module>
    import numpy as n, _miriad
ImportError: dlopen(/Library/Python/2.7/site-packages/aipy-2.1.0-py2.7-macosx-10.11-intel.egg/aipy/_miriad.so, 2): no suitable image found.  Did find:
	/Library/Python/2.7/site-packages/aipy-2.1.0-py2.7-macosx-10.11-intel.egg/aipy/_miriad.so: mach-o, but wrong architecture
>>> ^D

aipy was installed via easy_install. I also have macports on this machine if that matters.

I still have the output of the install if that is useful.

Cheers,
Randall

**Comment by dannyjacobs** [comment]
We've tested aipy installed via pip on 10.11.6 and 10.12 without seeing this issue.  Several minor fixes have been made to AIPY on the HERA-Team fork, try installing that one.
https://github.com/HERA-Team/aipy
If it errors, please post the full install message as well as the error.

Thanks,
~Danny

**Comment by bhazelton** [comment]
Has this issue been resolved?

**Comment by rbw42** [comment]
No, this is still a problem, but I don't know how to debug it. It probably has something to do with having macports installed, or (maybe, but not likely) my own copy of miriad installed.

**Comment by bhazelton** [comment]
Ok. One other option if you use anaconda is that Peter Williams has an aipy
conda package available. The command to install it from his channel is
```conda install -c pkgw aipy```. I found the conda package much more
reliable when I was trying to get continuous integration (on travis) and
read the docs working.

**Comment by bhazelton** [comment]
Addressed by comments above, the effort to remove aipy as a dependency is happening under issue #27.
