### ISSUE TITLE
benchmark file reads for miriad and uvfits

### ISSUE THREAD

**Issue by dannyjacobs** [HERA-Team/pyuvdata#109]

**Comment by adampbeardsley** [comment]
Adam L worked on this, and greatly improved the read/write times. @aelanman  - could you paste the latest benchmarks here then close the issue?

**Comment by aelanman** [comment]
The most recent line profile results are saved in the following file:
[https://github.com/HERA-Team/pyuvdata/edit/master/pyuvdata/tests/Line_Profiler_full.out](url)
