### ISSUE TITLE
loopback test on MWA uvfits

### ISSUE THREAD

**Issue by dannyjacobs** [HERA-Team/pyuvdata#11]

**Comment by jpober** [comment]
Waiting on FHD image.

**Comment by bhazelton** [comment]
The plan is to read in a Cotter uvfits with pyuvdata, then write out a new uvfits. Then run both the original and the new one through FHD and check that they're the same.

**Comment by bhazelton** [comment]
We do see differences in the two files, but they appear to be caused by floating point precision errors on the uvws (which are single precision in the Cotter files).
