### ISSUE TITLE
Dependency list in documentation is garbled

### ISSUE THREAD

**Issue by astrofrog** [HERA-Team/pyuvdata#118]
The bullets aren't shown correctly in the documentation in the dependency list:

<img width="454" alt="screen shot 2017-01-08 at 14 22 20" src="https://cloud.githubusercontent.com/assets/314716/21750569/f547b93e-d5ad-11e6-9176-1a19f7e366d1.png">

**Comment by bhazelton** [comment]
Fixed in latest commit.
