### ISSUE TITLE
Expand tutorial in documentation

### ISSUE THREAD

**Issue by astrofrog** [HERA-Team/pyuvdata#119]
At the moment, the only usage example provided in the docs is pretty minimal. This should be expanded and should for example show how to access the data programmatically once it is read in.

The tutorial as-is is not functional, because the import should be:

```python
from uvdata import UVData
```

In addition, I think ``read_miriad`` shouldn't take the ``miriad`` argument? (same comment for writing)

**Note:** I am reviewing the JOSS submission (https://github.com/openjournals/joss-reviews/issues/140) and I consider this to be a blocker.

**Comment by adampbeardsley** [comment]
The tutorial has been updated to the newer syntax, and expanded to include more file conversion examples and other functions, as well as plotting.
