### ISSUE TITLE
UVData class missing from API docs

### ISSUE THREAD

**Issue by astrofrog** [HERA-Team/pyuvdata#120]
The UVData class is missing from the API docs:

https://pyuvdata.readthedocs.io/en/latest/developer_docs.html

Since this appears to be the core class for the package, it should be documented.

There are other classes (e.g. UVParameter) that aren't documented either.

**Note:** I am reviewing the JOSS submission (https://github.com/openjournals/joss-reviews/issues/140) and I consider this to be a blocker.

**Comment by bhazelton** [comment]
This is fixed in the latest commit.
