### ISSUE TITLE
Ability to override checks for arrays and values from read_miriad()

### ISSUE THREAD

**Issue by jkerrigan** [HERA-Team/pyuvdata#127]
Working with miriad files that have been processed by using aipy scripts leaves certain values and parameters that don't match check parameters, e.g. pulling certain baseline types from miriad files leaves Nblts incorrect. The ability to override these checks directly from the read_miriad() function would be helpful.

**Comment by adampbeardsley** [comment]
Hi @jkerrigan 
I'm not exactly sure what you're looking to override. Would setting `run_check=False` in your `read_miriad` call do what you're asking for? If not, could you screen grab the call you're making and the output so I can better see what you're doing?

**Comment by bhazelton** [comment]
We've established that is caused by using an older version of pyuvdata to write the files. There have been changes to the Miriad data representation to reduce file bloat and we suspect that these changes are at the root of this problem.

**Comment by bhazelton** [comment]
@jkerrigan has this been resolved sufficiently for you?

**Comment by jkerrigan** [comment]
Yes, thank you.
