### ISSUE TITLE
Newline characters in history string

### ISSUE THREAD

**Issue by jpober** [HERA-Team/pyuvdata#13]
Newline characters in history string of uvfits file seem to break read_uvfits.

**Comment by jpober** [comment]
Need to reproduce

**Comment by jpober** [comment]
Occurs when trying to write out cotter files, on comment line:
COMMENT   FITS (Flexible Image Transport System) format is defined in 'Astronomy
COMMENT   and Astrophysics', volume 376, page 359; bibcode: 2001A&A...376..359H
Note that this line does NOT appear below HISTORY, currently trying to find a way to erase it from our object as a temporary workaround

**Comment by bhazelton** [comment]
This was fixed last week.
