### ISSUE TITLE
uvdata deprecation broken, old code using "import uvdata" still using ancient version 0.0.1

### ISSUE THREAD

**Issue by dannyjacobs** [HERA-Team/pyuvdata#140]
the installation of the deprecation error does not work as expected and the "uvdata" package is not being overwritten as intended.

This is a serious issue for any early adopters (like Prisim).

**Comment by bhazelton** [comment]
This might be fixed by adding a "uvdata" package in setup.py -- right now there's only a "pyuvdata" package. I'm happy to help, but it's hard for me to test with my setup.

**Comment by mkolopanis** [comment]
so if i install the latest pyuvdata build with:
 `python setup.py --old-and-unmanageable`

then try to import uvdata i get the import error. This doesn't really feel like a fix to me. I can not find a lot of info on that option but it stops python from installing the package (or packages) as an EGG

**Comment by bhazelton** [comment]
Our attempt to fix this failed. Remove uvdata folder from directory.
