### ISSUE TITLE
Update organization of calfits objects

### ISSUE THREAD

**Issue by plaplant** [HERA-Team/pyuvdata#166]
There is currently significant code duplication in a calfits object, since "delay"- and "gain"-type objects have a different number of dimensions. Delay-type should have a dummy index for frequency, so array dimensions are consistent. The ordering of the FITS data units should also be re-organized, so the header is in numerical order.

**Comment by bhazelton** [comment]
Is this done @plaplant?

**Comment by plaplant** [comment]
Yes, this was addressed by PR #170.
