### ISSUE TITLE
Port over DataContainer from hera_qm/vis_metrics.py to improve data interactivity

### ISSUE THREAD

**Issue by jsdillon** [HERA-Team/pyuvdata#167]
As a user, it would be very nice to have something like __getitem__ that allows one to select on baseline, polarization, channel, and time and get back a sensible numpy array. Also, it would be nice if __getitem__ is smart enough to know when the requested baseline is the conjugate of the one stored and return its np.conj().

**Comment by jsdillon** [comment]
While you're at it, what about a uvdata.get_ants() function that does the following:

np.unique(np.append(uv_in.ant_1_array, uv_in.ant_2_array))

**Comment by adampbeardsley** [comment]
Addressed in enhance_UI merge.
