### ISSUE TITLE
read_uvfits with cotter

### ISSUE THREAD

**Issue by aelanman** [HERA-Team/pyuvdata#18]
A few required parameters aren't in the header of uvfits files generated by cotter. These are _xyz_telescope_frame_, _spw_array_, and _vis_units_.

-Adam

**Comment by dannyjacobs** [comment]
Ok, we'll need to set defaults if they will be:
vis_units = UNCALIB
xyz_telescope_frame = ????
spw_array = [1]

**Comment by bhazelton** [comment]
For cotter files, we actually set xyz_telescope _frame = 'ITRF' after establishing that they were in that frame. For other uvfits files without this keyword we set xyz_telescope_frame = ????

Fixed in commit 5918a70
