### ISSUE TITLE
Make it possible to convert from miriad to uvfits without phasing the data

### ISSUE THREAD

**Issue by Trienko** [HERA-Team/pyuvdata#180]
It would be nice to allow miriad_to_uvfits.py not to phase the data before converting to uvfits, add an option to the scripts to either phase or not to phase.

**Comment by bhazelton** [comment]
I don't think it's possible to make a valid uvfits file that has drift data in it. By definition, uvfits files are phased to a single RA/Dec location, see AIPS memo 117 (there's a copy in our repo under docs/references). Page 8 specifically says 'The RA and DEC axes shall both have the corresponding nAXISm values of 1' meaning they can only have one phase center. This means that any code that uses uvfits files as inputs expects the data to be phased.

One work around approach would be to save each separate time as a separate uvfits file with the phase center RA and Dec set to be the Zenith RA and Dec for that time. You can easily split up the data by times  using the select function on UVData.
