### ISSUE TITLE
Allow for numpy integers in select function.

### ISSUE THREAD

**Issue by aelanman** [HERA-Team/pyuvdata#182]
Lines 736-737 of uvdata.py, in the select function, check that the list of tuples supplied as ant_pairs_nums are tuples of integers or longs.

There are times when the tuples passed will contain numpy integers. Though these should be perfectly compatible, the check on these lines complains that the list is invalid.

A minor issue, but I'd request that either numpy integers be allowed or a more useful error be given.

**Comment by bhazelton** [comment]
I'm having trouble finding the appropriate lines, because on the master branch, lines 736-737 are in the `__add__` function.

Can you make a new branch off of master with a test that fails because of this issue? That's the easiest way for me to figure out how to fix it.

**Comment by aelanman** [comment]
Ah, sorry. I haven't pulled in a while. I'll try to set up the test.

**Comment by bhazelton** [comment]
ok, thanks. I'll work on fixing it, but we really want a new test with this problem, not to replace an old test because we need both to work.
