### ISSUE TITLE
UVBeam test suite should be based on actual data files

### ISSUE THREAD

**Issue by bhazelton** [HERA-Team/pyuvdata#198]
As opposed to fake data. This can be fixed after the read_cst method is implemented.

**Comment by aelanman** [comment]
Based on the Zac's code in polskysim, I've written a script that reads in the Nicolas Fagnoni simulated E-field patterns for HERA and fills a UVBeam object. I'm not sure how read_cst is supposed to work, but I do have a hera beamfits file now. If someone else would be willing to check it, could that serve for tests?

**Comment by bhazelton** [comment]
This is fixed except for e-field healpix beams. Once conversion of e-field beams to healpix works we can finish this off.
