### ISSUE TITLE
size of calfits file quite large

### ISSUE THREAD

**Issue by nkern** [HERA-Team/pyuvdata#212]
Not sure if this is an urgent issue, but it seems like the size of calfits files are quite large, even when the size of the delay_array (which is the main information in the file) is not that large. For example, I have a a calfits file from HERA-19 with 56 time stamps (19 x 56 array), and the file is > 8 MB in size. I understand there are other arrays in the calfits file describing the observation and telescope, but is there a specific reason why it is > 8 MB in size? Or is that to be expected?

I ask because I'm writing some metrics for FirstCal in hera_qm and I would like to have an example calfits file in the test suite but I don't know if it is smart to have a ~10 MB file hanging around with us in the repo.

Let me know if there is a specific attribute I can cut from the file to make things a little leaner w/o losing delay_array information.

Thanks

**Comment by SaulAryehKohn** [comment]
Hi nkern,

When we were developing and testing hera_cal, we did a down-select in time (3 integrations) and frequency (256 channels) to significantly shrink the size of the miriad and calfits files. 

Given the way firstcal works, I'm guessing you don't want to get rid of frequency information (although maybe you could deal with slightly coarser delay bins). But maybe you could just grab a couple of integrations? It really depends on your use case.

**Comment by plaplant** [comment]
Also, in pyuvdata, there already is a full-size HERA delay file in the repo (`pyuvdata/data/zen.2457698.40355.xx.HH.uvc.fits`). So it's not unheard of to have a full file. That said, if you can work with a smaller test file, that's better.

Check out the `select` function defined in `uvcal.py` to see how to do the downselect easily. My guess is you'd want to cut down the number of time samples, so you could look at the `times` keyword.

**Comment by nkern** [comment]
So I'm just looking at calfits output from FirstCal, meaning I don't really care

**Comment by nkern** [comment]
sorry hit the comment button too soon:

I don't really care about the frequency information, I just want a delay solution per antenna per time, so I'll just eliminate the (19, 1, 1024, 56, 1) array full of zeros that seems to be eating up so much space.

**Comment by nkern** [comment]
In the calfits.py -- CALFITS class -- write_calfits function:

So it seems that the 8 MB of the CALFITS object comes from the  "secdata" array of zeros or ones in the 3rd HDU of the fits file (the ImageHDU). Is this array necessary to have? I think the file could go from 8 MB to ~ 500 KB if we just get rid of this one array. One idea is to give it instructions on how to generate this array when reading it in, rather than passing the full array itself.

**Comment by plaplant** [comment]
As you've surmised, the array you're pointing out is the `flag_array`, which is required by the file format. In general, it's unusual for the array to be all zeros or ones, so it's more straightforward to keep around in full.

It looks like the file that you're working with has 56 time samples (the second-to-last number in your `flag_array` shape). Unless your tests use all of these time samples, selecting just 3 of these (say the first three or last three) should shrink your file size down to ~500 KB. If you do want to use all time samples and antennas, I'm afraid you're stuck with the full 8 MB file.

**Comment by nkern** [comment]
Ok, thanks for the feedback!
