### ISSUE TITLE
Lat/Lon in degrees or radians

### ISSUE THREAD

**Issue by jpober** [HERA-Team/pyuvdata#22]
We've defined longitude/latitude as being in degrees, but our set_ functions in both directions seem to use radians.

**Comment by dannyjacobs** [comment]
Lets add a .deg() method that gives you degrees.

**Comment by piyanatk** [comment]
Why didn’t we use astropy units and quantity in the first place?

**Comment by jpober** [comment]
Fixed by adding angle attribute subclass with degree method.

**Comment by piyanatk** [comment]
Hi Judd,

I think I am only on hera-data. Which list should I send them to?

-Boom
