### ISSUE TITLE
Clarification needed: phasing to first time-slot

### ISSUE THREAD

**Issue by Trienko** [HERA-Team/pyuvdata#230]
I just need to ask some clarification on how the phasing to the first time-slot in miriad_to_uvfits.py works. 

1. Does one convert alt/az (i.e pointed to zenith) into ra/dec given the UTC of first time-slot, does this ra/dec now become your new field center to which you phase?
2. Does one simply convert the UTC of first time slot to LST, does this LST/ra value now become the ra  and the lat your dec of the new field center to which you phase?

For point 1 or 2 does one do J2000/J2016 conversion?

**Comment by bhazelton** [comment]
@Trienko I'm sorry this hasn't been answered before now. My reading of the code (I didn't write this part) is that if you read a miriad drift file and then write it to a uvfits file and set the `force_phase` keyword, then the RA and Dec in the observing epoch are calculated from LST and latitude. These observing epoch values are then converted to RA and Dec in J2000 and all the data are phased to that J2000 RA & Dec. Finally the data are written to a uvfits file where the J2000 RA and Dec are given in the header and the epoch is given in the header as 2000.

Does that answer your question? @jpober please correct me if you see any mistakes here.

**Comment by jpober** [comment]
That sounds right to me.  At least that sounds like we tried to do, but we still haven't gotten our phasing to agree perfectly with reference standards, so there is a (small) potential error lurking.

**Comment by bhazelton** [comment]
I think this has been addressed, so I'm going to close it. If you still have questions, feel free to reopen this issue or post another issue.
