### ISSUE TITLE
Clear objects when reading file

### ISSUE THREAD

**Issue by adampbeardsley** [HERA-Team/pyuvdata#237]
When reading a file using one of our objects (e.g. UVData), we should be resetting the object before reading. I think there are possible scenarios where old data can propagate through a read, for example extra_keywords, or possibly if the current phase type is drift but one then reads a tracking file. To be safe we should be clearing everything out.

**Comment by bhazelton** [comment]
I'm having a hard time coming up with a test that fails because of this. Do you have an example?

**Comment by adampbeardsley** [comment]
I don't have any example where this would fail (and haven't been able to create one on purpose). The examples I gave in the original issue turned out to not actually be a problem. I was more concerned that we're doing this passively, without explicitly clearing data. But maybe we are and I just didn't realize it.

**Comment by bhazelton** [comment]
I was trying to make one with uvfits and I think there we've protected ourselves because we set missing keywords to None (with things like `self.x_orientation = hdr.pop('XORIENT', None)`) but I think you're right to be concerned in general. I'll keep working on finding a test that fails.

**Comment by adampbeardsley** [comment]
Maybe for the test you could make a non-sensical uvparameter and make sure that gets cleared when you read a new data file?

**Comment by bhazelton** [comment]
I suppose I could. That's actually a different thing than I was worried about, but we probably do want that behavior as well.

**Comment by bhazelton** [comment]
Oh, wait. I think this is already taken care of, because in the read methods on UVData, the first thing that happens is that there's a new object made and the data are read into that object (e.g. line 1320 of uvdata.py)

**Comment by adampbeardsley** [comment]
It looks like it comes down to:
```    
def _convert_from_filetype(self, other):
    for p in other:
        param = getattr(other, p)
        setattr(self, p, param)
```
So as long as `other` has the same parameters as `self`, we should be good. But if for some reason `self` has extras, they won't get overwritten. But is that possible?

**Comment by bhazelton** [comment]
In principal you're right, although I'm much less worried about extra parameters hanging around because they won't get written to any files because they aren't a known parameter.

But I'm also finding that I can't actually implement that test because it errors on the next read in a way I didn't expect but effectively prevents this from being an issue. I did the following:
```    uvtest.checkWarnings(uv_in.read_uvfits, [testfile], message='Telescope EVLA is not')
    from pyuvdata import parameter as uvp
    uv_in._test_param = uvp.UVParameter('test_param', description='testing',
                                        expected_type=int)
    this_param = getattr(uv_in, '_test_param')
    attr_name = this_param.name
    setattr(uv_in.__class__, attr_name, property(uv_in.prop_fget('_test_param'),
                                                 uv_in.prop_fset('_test_param')))
    uv_in.test_param = 1
    uvtest.checkWarnings(uv_in.read_uvfits, [testfile], message='Telescope EVLA is not')
    uvtest.checkWarnings(uv_out.read_uvfits, [testfile], message='Telescope EVLA is not')
    nt.assert_equal(uv_in, uv_out)
```
And it errored on the 3rd to last line with the following message:
```
Traceback (most recent call last):
  File "//anaconda/envs/py2/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/bryna/Projects/Physics/HERA/pyuvdata/pyuvdata/tests/test_uvfits.py", line 102, in test_readwriteread
    uvtest.checkWarnings(uv_in.read_uvfits, [testfile], message='Telescope EVLA is not')
  File "/Users/bryna/Projects/Physics/HERA/pyuvdata/pyuvdata/tests/__init__.py", line 64, in checkWarnings
    retval = func(*func_args, **func_kwargs)  # Run function
  File "/Users/bryna/Projects/Physics/HERA/pyuvdata/pyuvdata/uvdata.py", line 1320, in read_uvfits
    uvfits_obj = uvfits.UVFITS()
  File "/Users/bryna/Projects/Physics/HERA/pyuvdata/pyuvdata/uvdata.py", line 315, in __init__
    super(UVData, self).__init__()
  File "/Users/bryna/Projects/Physics/HERA/pyuvdata/pyuvdata/uvbase.py", line 40, in __init__
    for p in self:
  File "/Users/bryna/Projects/Physics/HERA/pyuvdata/pyuvdata/uvbase.py", line 128, in __iter__
    not callable(getattr(self, a))]
  File "/Users/bryna/Projects/Physics/HERA/pyuvdata/pyuvdata/uvbase.py", line 68, in fget
    this_param = getattr(self, param_name)
AttributeError: 'UVFITS' object has no attribute '_test_param'
```
That 3rd to last line was line 102 in test_uvfits.py when I ran it.

So I think this is actually a non-issue, but I didn't expect that exact error message.

**Comment by adampbeardsley** [comment]
Ok, well if it's a non-issue I'm happy to close it.
