### ISSUE TITLE
MIRIAD "ischan", "nschan" keywords not created when writing data

### ISSUE THREAD

**Issue by pkgw** [HERA-Team/pyuvdata#245]
The raw HERA datasets correctly include the UV variables [nschan](https://github.com/pkgw/viskit/blob/master/doc/uvvars.txt#L213) and [ischan](https://github.com/pkgw/viskit/blob/master/doc/uvvars.txt#L162). However, by the time that we get to the `.uvOR` data, those variables have disappeared.

To be determined: whether pyuvdata is at fault here, or whether aipy is.

**Comment by plaplant** [comment]
I think to fix this we just have to move them from `other_miriad_vairables` to `default_miriad_variables` in `miriad.py`. I'll make a branch and see if this fixes things.

**Comment by plaplant** [comment]
Fixed with PR #246.
