### ISSUE TITLE
Add support for saving delay offsets in UVCal object

### ISSUE THREAD

**Issue by plaplant** [HERA-Team/pyuvdata#247]
UVCal delay-type calibration files only save a single number per antenna/time/Jones entry in the `delay_array` object, which is the delay determined by firstcal. However, firstcal now supports identifying antennas rotated by 180 degrees, which can be encapsulated as a delay offset. We should add support for saving the offsets for each antenna/time/Jones entry as an optional array for delay-type files.

**Comment by bhazelton** [comment]
@plaplant I'm happy to help with this change, but I'm not sure I fully understand it. What should the dimensionality of these offsets be? And how should they be used when constructing gain-type solutions from delay-type solutions?

**Comment by plaplant** [comment]
I think this is actually no longer necessary. The firstcal files are now saved as gain-type (so they have a frequency axis of size `Nfreqs` instead of 1), and things like firstcal_metrics are able to infer the delay and the offset from the gains. So since this issue is not needed as a practical matter, I think the effort of implementing it could probably be better spent elsewhere. But if other people are interested in this, I can pitch in to do some of this work.

**Comment by bhazelton** [comment]
Ok, I'm going to close it and it can be re-opened in the future if needed.
