### ISSUE TITLE
Known telescopes list

### ISSUE THREAD

**Issue by jpober** [HERA-Team/pyuvdata#25]
Add parameters for known telescopes (e.g. altitude of PAPER)

**Comment by jpober** [comment]
Telescope list should contain:

Telescope name
Array position (XYZ telescope or lat/lon/alt)
Array position frame
Instrument (maybe different from telescope name?)

Maybe:

Antenna positions (but what about reconfigurable/growing telescopes?)

**Comment by jpober** [comment]
Write a function set_telescope, implement in reads.

**Comment by bhazelton** [comment]
Closed with latest pull request.
