### ISSUE TITLE
Add select-on-read (ala miriad)

### ISSUE THREAD

**Issue by dannyjacobs** [HERA-Team/pyuvdata#255]
somehow we need to support the kind of workflow where, if one knows the data one wants from a file we can just read out a small subset.

the miriad select function works by specifying filters and then only reading the matching records from the file.  See aipy.miriad.uv.select() or aipy.scripting.uv_selector()

**Comment by bhazelton** [comment]
This has been done on the uvfits side, but the Miriad part remains to be done (thus the issue name change)

**Comment by bhazelton** [comment]
The miriad part was done in PR #335
