### ISSUE TITLE
Add support for more CST files

### ISSUE THREAD

**Issue by adampbeardsley** [HERA-Team/pyuvdata#265]
There appears to be a wide range of formats for the CST headers. It would be awesome to find some definitive document outlining this range, but for now we should make sure we support various files we come across. For example, one file I have has a header that looks like:
`Theta [deg.]  Phi   [deg.]  Abs(Dir.)[dBi   ]   Abs(Theta)[dBi   ]  Phase(Theta)[deg.]  Abs(Phi  )[dBi   ]  Phase(Phi  )[deg.]  Ax.Ratio[dB    ] `
This breaks the current read_cst function because of the `Abs(Dir.)` column, and the units dBi.

**Comment by bhazelton** [comment]
The consensus is that instead of supporting all kinds of CST beam files we should instead document how to export the kind of files we support. That is being tracked in issue #279, so I'm closing this issue in favor of that one.
