### ISSUE TITLE
Remove aipy dependency

### ISSUE THREAD

**Issue by jpober** [HERA-Team/pyuvdata#27]
May or may actually but possible, but a good goal

**Comment by jpober** [comment]
Could possibly just use miriad.py from aipy (with proper attribution/licensing)

**Comment by bhazelton** [comment]
@aelanman whats the status here?  Are there any issues we can help solve?

**Comment by aelanman** [comment]
I've looked a little into modifying the miriad code for Windows compatibility, but without a Windows machine I'm not sure of how to test it. I've also investigated the option of writing a pure-python MIRIAD reader, but that's a much more involved project.

The remove_AIPY branch has my changes in it.

**Comment by bhazelton** [comment]
There's another continuous integration service for this (like Travis) called Appveyor. I tried to get it working before concluding that I could not because of this aipy issue. I moved the file for it into the ci/ directory, I'm happy to work with you on getting it set up again.

**Comment by aelanman** [comment]
That sounds useful. To make sure I understand you correctly, you're saying we'd modify the miriad C code to work on Windows?

It looks to me like there are a few include files in miriad that would need an extra function added to read files in Windows, so it might be possible.

**Comment by bhazelton** [comment]
My (limited) understanding is that we'll need to make some modifications to the C code to allow it to be compiled properly in Windows. I don't know much about this but I do have some people I can potentially ask if we can't figure it out by googling.

**Comment by aelanman** [comment]
It's been a while since I worked with C, but I'll try to find what needs to be changed :)

**Comment by bhazelton** [comment]
This is done as of PR #371
