### ISSUE TITLE
Improve readme

### ISSUE THREAD

**Issue by bhazelton** [HERA-Team/pyuvdata#29]
Add at least some basic info describing the purpose and general structure.
Add some examples.

**Comment by adampbeardsley** [comment]
Potential journal for publishing code: http://joss.theoj.org/
Relies on documentation for the code review. Should reference this when writing the readme.

**Comment by dannyjacobs** [comment]
have added a sphinx build in docs/ 
to update the docs:
run make_parameters.py to generate the parameters page
the readthedocs page is built automatically when you push to github

**Comment by bhazelton** [comment]
I think we can close this issue. There could always be more documentation (the readme is still too short and we need more examples) but the docs on readthedocs look pretty good. We might need to revisit this for the paper, but I think that's separate from version 1.0

**Comment by dannyjacobs** [comment]
Agreed.

**Comment by jpober** [comment]
We don't actually have a readme it seems, and readthedocs is out of data.  So let's re-open.

**Comment by dannyjacobs** [comment]
README is done according to http://joss.theoj.org/about#author_guidelines and is approved by the High Council.  It still needs to be ported to readthedocs, but we're closing this issue.
