### ISSUE TITLE
I think this docstring is wrong.

### ISSUE THREAD

**Issue by jsdillon** [HERA-Team/pyuvdata#294]
https://github.com/HERA-Team/pyuvdata/blob/5939016012b04af5d49183b330f7b1510d41baad/pyuvdata/uvcal.py#L350

**Comment by jsdillon** [comment]
Shouldn't it be "redundant" not "sky"?

**Comment by plaplant** [comment]
Yes, there’s a PR to fix this, it just needs to be approved and merged

**Comment by plaplant** [comment]
Fixed with PR #293.
