### ISSUE TITLE
standardize history writing

### ISSUE THREAD

**Issue by nkern** [HERA-Team/pyuvdata#298]
A take-away from 2/13 HERA analysis telecon was that we need to standardize history writing to make history more human-readable. I think this is actually a `hera_cal` issue, but I was asked to make the issue here. How do people feel about this?

**Comment by bhazelton** [comment]
I'm not sure I understand what the suggested changes are. I'm happy to support more readable history, as long as it doesn't break things.

**Comment by bhazelton** [comment]
@nkern can you elaborate on what this issue is requesting?

**Comment by nkern** [comment]
Well, someone asked me to open an issue on `pyuvdata` on making histories more human readable. but it felt more like: we need to discuss further how do this. I personally feel like this is `hera_cal` issue, or an RTP issue, and not a `pyuvdata` issue. but people asked me to open it here...

**Comment by bhazelton** [comment]
ok, who should we bring into the conversation about what is desired on pyuvdata? I feel like if it's an issue on pyuvdata it implies desired changes or clarifications in the pyuvdata code base.

**Comment by nkern** [comment]
well, I think it was @dannyjacobs that asked me to make the issue, but also probably @plaplant and @adampbeardsley would feel like they have a stake in it as well.

**Comment by nkern** [comment]
I say this is an RTP or `hera_cal` issue because from my understanding those are the tools that are actually **doing the history writing**, whereas the `history` attribute of a `UVData` object is merely a placeholder for whatever you want to put in there. perhaps this is an issue I can close on `pyuvdata` and an issue I can raise in the new `hera_opm` module Paul is working on. If people are okay with that I'm happy to do so

**Comment by adampbeardsley** [comment]
Yeah, trying to remember what we wanted exactly. I think the idea was that we want something a bit easier to read than a block of text. Of course right now it's up to the user (RTP, hera_cal, etc) to write what they want. But I also wonder if we need some changes in pyuvdata to enable this. For example, I think we strip out new lines because the files introduce spurious ones. Not sure what the answer is there, but it would be nice to purposely have formatting that pyuvdata preserves.

**Comment by bhazelton** [comment]
So I'm don't think we do strip new lines, except when we're testing whether blocks of history text are already present.

**Comment by bhazelton** [comment]
Reading miriad.py and uvfits.py, we don't appear to be stripping new line characters, only adding some if they don't exist.

**Comment by adampbeardsley** [comment]
ok, then yeah, I'm not sure why we made this a pyuvdata issue. Let's see if @plaplant or @jsdillon remember if there was anything specific before we close and move it to a different repo.

**Comment by jsdillon** [comment]
I think the issue was more like whether we had automated ways of parsing the history and turning it into a human-readable reconstruction of what happened, perhaps with a more tabular representation of the commands used, the git hashes, etc.

I honestly don't think we know exactly what we want, so perhaps we should wait and see how people use and/or struggle to use the histories before we decide to reorganize them.

**Comment by bhazelton** [comment]
I think at heart, any such parsing may have to live in with the code that creates the history. There are infinite ways to write histories and what is relevant depends highly on the code and organization.  That said, I'm **strongly** in favor of adding anything that is reasonably standard and likely to need to be accessed in a machine-readable way as either an extra keyword or as an optional parameter on the object. Extra keywords will work well for anything that is not a large array. If large arrays are needed for something we can certainly consider adding optional parameters to ensure that they are preserved properly by pyuvdata.

**Comment by bhazelton** [comment]
@plaplant I think if there are standard things we want to access like this, they should be added as extra keywords or we should add optional parameters to the object to store and transmit them.

**Comment by plaplant** [comment]
So maybe we can go the extra keywords route for any RTP/offline processing that happens? At any rate, it sounds like we all agree it's not a pyuvdata issue.

**Comment by bhazelton** [comment]
Ok, it sounds like we agree that this issue should be closed. I will note that pyuvdata currently regularly adds information about the pyuvdata version to the histories. I think there's a case to be made for adding that to extra keywords if people need it to be more machine readable.
