### ISSUE TITLE
Add support for drift scan data -- ie don't force a single RA/DEC phase center

### ISSUE THREAD

**Issue by bhazelton** [HERA-Team/pyuvdata#3]
Also add support for keeping track of LSTs over observation

**Comment by dannyjacobs** [comment]
This is key to HERA commissioning.

**Comment by dannyjacobs** [comment]
read_miriad allows reading of drift scans, it just does not set ra dec
write_uvfits should error if ra and dec are not set.

**Comment by jpober** [comment]
Suggested phasing rule: if alt/az is set and ra/dec  are None, then its a drift scan

**Comment by jpober** [comment]
Added.  Format is as follows:
If set, phase_center_ra and phase_center_dec indicate tracked scan.
Otherwise, if set, zenith_ra and zenith_dec indicate drift.  Both of these are arrays even though dec is obviously a constant.
Multisource files are not supported.
