### ISSUE TITLE
internal inconsistency on `UVCal.ant_array` attribute

### ISSUE THREAD

**Issue by nkern** [HERA-Team/pyuvdata#305]
There is an inconsistency with how the `ant_array` attribute of the `UVCal` object is defined on the docs and how it is used in practice. On the docs its defined as an array that holds the **antenna indices** (not their numbers!) for the `self.gain_array`. In practice we are using it as just a copy of `antenna_numbers` (see how the `UVCal.select` function is defined).

We will have a PR soon on `hera_cal` that fixes this in our `io` module such that `ant_array` is used as defined on the `pyuvdata` docs, but that consistency also needs to be fixed within the `UVCal` object itself. Because `UVCal` doesn't have a `get_gain` function this hasn't been a problem in practice, but it does pose a potential problem with the `select` function. I'm happy to submit a PR for this if people also agree this is something we need to fix..

**Comment by bhazelton** [comment]
We should talk about whether the docs should be fixed or the code should be fixed.

**Comment by nkern** [comment]
Up to you! If we want to just change the docs then I need to go back and edit `hera_cal.io.load_cal` to accommodate that, if on the other hand we want to just go in and change how `ant_array` is being used in `UVCal` I'm fine w/ that too: either way I'll be writing some code :)

**Comment by nkern** [comment]
From a HERA analysis pipeline perspective, its probably easiest to leave the `UVCal` object as it stands and to just change the documentation on `ant_array`. If that's ok w/ you @bhazelton I can submit a PR for that...

**Comment by bhazelton** [comment]
I think it's ok, but I need to look at it and think about it a little more, I'm not sure what all the implications are. I'd also like to get @plaplant's views on it.

**Comment by bhazelton** [comment]
I think it's possible that the docs were just written wrong -- that they don't convey the actual intent.

**Comment by nkern** [comment]
yes, from all of the code using the `UVCal.ant_array` attribute it seems that the mutually understood purpose is a version of `antenna_numbers` that exist in the data with ordering matching `gain_array`, whereas `antenna_numbers` is a full Nants_telescope length array. in many cases these are the same, but it would be good to clear this up in the documentation...

**Comment by bhazelton** [comment]
So the description for `antenna_numbers` says "There must be one entry here for each unique entry in ant_array, but there may be extras as well." This suggests to me that the docs on `ant_array` are wrong and they should be antenna numbers.

**Comment by nkern** [comment]
right, with the *important* distinction that `ant_array` should have ordering that matches the zeroth axis of `gain_array`

**Comment by nkern** [comment]
but also that description of `antenna_numbers` is a little misleading, because as its being used, there should be no repetition  of elements in `ant_array`: it itself contains unique elements.

**Comment by bhazelton** [comment]
Absolutely. I think it's possible that the term `indices` was used (incorrectly) to try to avoid confusion with the parameter named `antenna_numbers`. Can you make a PR to fix the docs and we'll make sure to get other interested parties to check them?

**Comment by nkern** [comment]
👍

**Comment by bhazelton** [comment]
this was addressed in PR#306
