### ISSUE TITLE
Phasing uses pyephem for lst

### ISSUE THREAD

**Issue by jpober** [HERA-Team/pyuvdata#31]
Should switch to astropy and use Bryna's IERS_A table fix

**Comment by dannyjacobs** [comment]
this needs to be re-avaluated.  Now we're also using ephem.Observer which also doesn't have the current leap second table.

**Comment by bhazelton** [comment]
Too many questions about how pyephem works, including lack of leap seconds and concerns about which ra/dec values to use. Consider switching to skyfield.

**Comment by jpober** [comment]
Astropy may provide the functionality needed.

**Comment by bhazelton** [comment]
should be addressed as part of fixing phasing, see issue #148.
