### ISSUE TITLE
Key error: 'epoch' on certain files

### ISSUE THREAD

**Issue by jsdillon** [HERA-Team/pyuvdata#320]
Here's the minimum example that reproduces the error:

```
from pyuvdata import UVData
uvd = UVData()
uvd.read_miriad('/lustre/aoc/projects/hera/H1C_IDR2/IDR2_1/2458104/zen.2458104.38649.xx.HH.uvOCRS')
```

which gives us:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/users/jsdillon/anaconda2/envs/hera/lib/python2.7/site-packages/pyuvdata-1.2.1-py2.7.egg/pyuvdata/uvdata.py", line 1465, in read_miriad
    phase_type=phase_type)
  File "/users/jsdillon/anaconda2/envs/hera/lib/python2.7/site-packages/pyuvdata-1.2.1-py2.7.egg/pyuvdata/miriad.py", line 671, in read_miriad
    self.phase_center_epoch = uv['epoch']
  File "/users/jsdillon/anaconda2/envs/hera/lib/python2.7/site-packages/aipy/miriad.py", line 183, in __getitem__
    type = itemtable[name]
KeyError: 'epoch'
```

Interestingly, I also get the error on `zen.2458104.38649.yy.HH.uvOCRS`. I do not get the error for the 'xy' or 'yx' files, but I do get some warnings:
```
Mean of empty slice.
invalid value encountered in double_scalars
```

I do not get the error for neighboring files in time. I also do not get the error for the `.uv` that these are created from using `hera_cal.apply_cal` (which uses `hera_cal.io.update_vis`) which keeps most of the properties in a pyuvdata object unmodified (including the epoch as far as I know).

Any thoughts?

**Comment by jsdillon** [comment]
Also, for what it's worth, I don't think this a problem with my python installation. We get the same error when running the pipeline. See `/lustre/aoc/projects/hera/H1C_IDR2/IDR2_1/2458104/zen.2458104.38649.xx.HH.uv.DELAY.xx.log`

**Comment by bhazelton** [comment]
It sounds like the epoch keyword isn't being written to the miriad file, which is bad. Is the miriad file you're reading in one that was written by pyuvdata?

**Comment by bhazelton** [comment]
Ah, this looks like it's only assumed to be present for phased files, which should definitely have an epoch. If the file is drift mode, the epoch variable does not need to be present. Do you expect these files to be phased or drift?

**Comment by jsdillon** [comment]
Well, here's the strange thing: this file was created by reading in a miriad file (so that should be drift, right?) into a UVData object, modifying its visibilities, flags, and history, and then writing it back out using pyuvdata. Here's the code for that: https://github.com/HERA-Team/hera_cal/blob/4d13364a271abcf935d883fb77511d60d20ea721/hera_cal/io.py#L326

So the epoch should be the same as the file it was built from, namely zen.2458104.38649.yy.HH.uv

The apply_cal log for the step before it looks unremarkable: 
```more /lustre/aoc/projects/hera/H1C_IDR2/IDR2_1/2458104/zen.2458104.38649.xx.HH.uv.CAL_SMOOTH_APPLY.xx.log
Thu Mar 29 04:28:14 MDT 2018
apply_cal.py zen.2458104.38649.xx.HH.uv zen.2458104.38649.xx.HH.uvOCRS --new_cal zen.2458104.38649.xx.HH.uv.smooth_abs.calfits --flags_npz=zen.2458104.
38649.xx.HH.uvOCR.flags.applied.npz --clobber --filetype=miriad --gain_convention=divide
Thu Mar 29 04:29:10 MDT 2018
```



This step worked 5214 times and failed only 18 times in the most recent pipeline. So it's something pretty weird.

**Comment by bhazelton** [comment]
This is weird. Miriad files support both drift and phased data. Unfortunately which kind of file it is has to be inferred (although there is a keyword to `read_miriad` called `phase_type` that can be set to `drift` or `phased` if you know what you're dealing with).

The way it's inferred is by checking to see if the RA changes in the file (if it changes it's a drift file, if not it's a phased file). If there's only one time, of course, the RA doesn't change, but in that case it checks to see if the `epoch` keyword is present (if it is present it's assumed to be phased, otherwise it's treated as a drift file).

I can look at the specific file tomorrow to try to understand more, but just reading the code, this error really shouldn't be happening spontaneously.

**Comment by jsdillon** [comment]
Agreed... it's pretty weird. Thanks for looking into it!

**Comment by bhazelton** [comment]
So I think this has to do with flagging. I'm working to confirm this now, but the RA list that is used to check infer drift vs phased file type only included unflagged RAs.

**Comment by bhazelton** [comment]
Josh, I think PR #323 fixes this problem. Can you check it out?
