### ISSUE TITLE
documentation error

### ISSUE THREAD

**Issue by nkern** [HERA-Team/pyuvdata#354]
In the `pyuvdata.UVData` documentation, the `baseline_array` attribute says the following

"Array of baseline indices, shape (Nblts), type = int; baseline = 2048 * (ant2+1) + (ant1+1) + 2^16"

which should read w/ `ant1` and `ant2` switched.

**Comment by bhazelton** [comment]
Thank you for catching this @nkern. Can you review the PR to fix it? (#357)
