### ISSUE TITLE
Required type for "instrument"

### ISSUE THREAD

**Issue by aelanman** [HERA-Team/pyuvdata#37]
I keep getting an error that says that the required type for instrument is an int. In uv.py, I see that instrument is set to be a string, and that's what I've been assigning to it, but the checker still tells me it should be an int:

ValueError: UVProperty instrument is not the appropriate type. Is: <type 'str'>. Should be: <type 'int'>

**Comment by aelanman** [comment]
I was able to fix this -- The expected_type attribute wasn't set for "instrument", so it defaulted to int.

**Comment by adampbeardsley** [comment]
@aelanman: Did you fix it in pyuvdata, or just in how you were using it? This should not be the default behavior, but it's easy to fix.

**Comment by aelanman** [comment]
I fixed it in pyuvdata. Line 250 of uv.data, I added expected_type=str to the definition.

**Comment by adampbeardsley** [comment]
Ok, I will also put a check in the defaults. Right now there are options to set "form" (ie, size), and type, but the defaults can contradict.

**Comment by aelanman** [comment]
I'm getting a new error now, with the polarization array. It looks like it's not calculating the expected_size correctly. The array has four elements and Npols is 4, but it's telling me they don't match.

**Comment by adampbeardsley** [comment]
Could you print a couple things for me (assuming your UVData object is called `uv_object`):
`print uv_object.Npols`
`print uv_object.polarization_array.value.shape`
`print uv_object.polarization_array.value.dtype`
`print uv_object.polarization_array.expected_size(uv_object)`
Also, could you copy-paste the exact error message?

**Comment by aelanman** [comment]
Okay, I found and fixed one problem with my code. The polarization_array was a list, not a numpy array, in my version.

Fixing that, this is what I get:

4
(4,)
float64
()
Traceback (most recent call last):
  File "./uvfits_zeros_gen.py", line 201, in <module>
    uvd.write_uvfits(ofile)
  File "/users/alanman/pyuvdata/uvdata/uv.py", line 927, in write_uvfits
    self.check()
  File "/users/alanman/pyuvdata/uvdata/uv.py", line 644, in check
    raise ValueError('UVProperty ' + p + 'is not expected size.')
ValueError: UVProperty polarization_arrayis not expected size.

**Comment by adampbeardsley** [comment]
Offline back-and-forth revealed that @aelanman is setting the polarization_array.value using setattr. Somehow the code is changing polarization_array.form (maybe somewhere else in the code?) because before the setattr, `polarization_array.form = ('Npols,')`, as it should. Needs more troubleshooting.

**Comment by aelanman** [comment]
It turns out that I was overwriting the polarization_array object with another UVProperty object. The form was being lost as a result. It's not an issue with pyuvdata.
