### ISSUE TITLE
uvbeam._get_beam no longer supports forming pseudo-Stokes map from linear pol maps

### ISSUE THREAD

**Issue by nkern** [HERA-Team/pyuvdata#384]
This is causing `master` on `hera_pspec` to fail. Was there a reason why this was taken away? @bhazelton @Chuneeta @philbull

**Comment by nkern** [comment]
Ah okay I think I see: now we start w/ e-field beams and run `uvbeam.efield_to_pstokes` to get pseudo-stokes beams, which we can then make into power beams via `efield_to_power`. This will require a little bit of work in `hera_pspec` to utilize this new functionality.

**Comment by Chuneeta** [comment]
Yes @nkern you are right. It now formed all pseudo-Stokes beam using the efield beam. So you need to call the function efield_to_pstokes to make pseudo-stokes beam. This the reason hera_pspec is failing. I will work on the PR to change all the 'pI' calls to 'xx' in the units tests and I think the tests should not fail. I will also work on updating the polarization part in hera_pspec.

**Comment by nkern** [comment]
@Chuneeta Okay, good to get confirmation on my suspicions. I don't think changing all the `pI` calls to `xx` will be good, though, because there are some tests that are specifically designed to test that pseudo-Stokes parameters work. We should only change tests that are testing code that is agnostic to the input polarization. 

There will be some minor infrastructure we need to include in `here_pspec` in the `PSpecBeamUV.power_beam_sq_int` functions. I'll push something up and you can have a look at what I mean..

**Comment by nkern** [comment]
@Chuneeta @bhazelton one thing I'm noticing is that the output of `UVBeam.get_beam_area` is complex. It has zero imaginary component, but is still complex, meaning that in `hera_pspec` our $\Omega_p$ is also complex. Can @Chuneeta you write a small PR making sure that the output of `UVBeam.get_beam_area` and `UVBeam.get_beam_sq_area` is casted into real before being returned? I'm working on the `hera_pspec` side of things now..

**Comment by nkern** [comment]
Ah okay, I think I see the reason now. So in *almost* all cases the output of `UVBeam.get_beam_area` has zero imaginary terms, _except_ for when `pol='XY'` and `pol='YX'`, then it has non-zero imaginary terms and is truly complex. Even the `pol='pI', pol='pU', pol='pQ'` and `pol='pV'` have zero imaginary terms.

This means that our power spectrum scalar will also be complex. Did we agree to use only real component of $\Omega_p$ for now? If so I can put the casting in to real on the `hera_pspec` side of things and `pyuvdata` doesn't need to change..

**Comment by nkern** [comment]
See PR 143 in `hera_pspec`. I think this is no longer a `pyuvdata` issue, so I'm going to close this.
