### ISSUE TITLE
UVData.read_miriad blows up memory more than it should

### ISSUE THREAD

**Issue by FoxFortino** [HERA-Team/pyuvdata#388]
Loading one night's worth of one polarization of `.uvOCRS` IDR2.1 data, all at once with `read_miriad`,  takes about 140GB of RES memory (according to `top` on herapost-master) even though `du` says the files only should take 47GB. Is there a memory leak?

**Comment by bhazelton** [comment]
I suspect this is the same as what's being discussed in issue #383

**Comment by dannyjacobs** [comment]
Its actually the memory use issue #227

**Comment by bhazelton** [comment]
closing in favor of #227
