### ISSUE TITLE
Sanity check optional?

### ISSUE THREAD

**Issue by jpober** [HERA-Team/pyuvdata#43]
Could we make sanity checks optional?  For example, I get insane values for uvw_array with a miriad file containing one baseline 0_0 (i.e. an autocorrelation).  I'd like to maybe just ignore the sanity check in this case, rather than try to work around it, because it is admittedly a pathological test.

**Comment by adampbeardsley** [comment]
Added this option in commit `e17f324`. Use `run_check` and `run_sanity_check` boolean option to read/write functions to turn checks off (on by default). Can also call check directly and use `run_sanity_check` to turn sanity check off. Let me know if this works.

**Comment by jpober** [comment]
Seems to work, I can use run_sanity_check=False to avoid errors I was getting with certain files.  Thanks!
