### ISSUE TITLE
CASA 4.6 can't read our antenna tables

### ISSUE THREAD

**Issue by jpober** [HERA-Team/pyuvdata#49]
With any pyvudata generated uvfits, we get an error, the key message of which seems to be:

SEVERE  ms::fromfits    Exception: (1-based) antenna 0 exists in the
visibility data, but there is no  record which references it in the FITS
AN table. Cannot proceed.

Unlike AIPS and uvfits, CASA is zero-indexed.  Is it possible we're using one-indexed antenna numbers instead of zero-indexed antenna names, or something like that? 

Note that this was not an issue with CASA 4.5, but only 4.6.

**Comment by jpober** [comment]
Perhaps related to similar failures seen with AIPS.  To quote Eric Greisen:

> VPLOT1: ANFIND: ODD PAPER    126      0.000E+00 0.000E+00 0.000E+00
> VPLOT1: ANFIND: ODD PAPER    127      0.000E+00 0.000E+00 0.000E+00
> VPLOT1: ANREFM: NO ANTENNA OR ARRAY RECOGNIZED
> AIPS 1: Resumes
>> VPLOT1: TABINI: REQUESTED AN FILE *** DOES NOT EXIST
> VPLOT1: ANINI: ERROR   2 FROM TABINI OPCODE = READ
> VPLOT1: ANINI: ERROR   2 INITIALIZING ANTENNA TABLE FOR READ
> VPLOT1: GETANT: ERROR  2 OPEN-FOR-READ AN FILE
> VPLOT1: TABINI: REQUESTED AN FILE *** DOES NOT EXIST
> VPLOT1: ANINI: ERROR   2 FROM TABINI OPCODE = READ
> VPLOT1: ANINI: ERROR   2 INITIALIZING ANTENNA TABLE FOR READ
> VPLOT1: ANTIN: ERROR IN OPEN AN-FILE IERR =      2
> VPLOT1: Purports to die of UNNATURAL causes
>

Surprising it did not abort - the limit on number of antennas is 90.

But I looked at your antenna file and it is a mess.  There is an antenna
number 0 - but that is not allowed - antennas are things and so count
from 1.  The array center is 0 (center of the Earth) which is what VLBI,
EVLA, etc do these days.  But the antenna BX,BY,BZ values put the
antennas within 100 meters of the center of the Earth.  Numbers more
like a few times 10**6 are what one expects.  The ODD PAPER remarks are
because some of the 127 antennas have position 0,0,0.

The station number 0 is causing the failure in VPLOT, curiously with two
different compilers.  I rebuild my version of aips (on primate) with 128
as MAXANT but it still does not work for VPLOT because of
the 0.

**Comment by bhazelton** [comment]
I think I may have fixed this in a recent commit, waiting on another round of Jonnie-Carilli testing

**Comment by jpober** [comment]
After Bryna's fix, bug no longer occurs in CASA 4.6.  Other AIPS bugs may be present.
