### ISSUE TITLE
Conjugation

### ISSUE THREAD

**Issue by jpober** [HERA-Team/pyuvdata#50]
From the miriad documentation:

> The current antenna baseline
> Baseline is stored as 256 ∗ ant1 + ant2 or
> 2048 ∗ ant1 + ant2 + 65536
> The uv coordinates are calculated as
> uvw = xyz(ant2) − xyz(ant1).
> Note that this is different from the AIPS/FITS convention
> (where uvw = xyz(ant1) − xyz(ant2)).
> When writing this variable, software must ensure that
> ant1 < ant2.
> baseline is also known as preamble(4) or preamble(5)

This could cause two separate conjugation issues:

(1) uvws all have opposite sign from uvfits; we must determine sign convention
(2) ant2 > ant1 is allowed by uvfits (and pyuvdata), so these baselines will be conjugated

**Comment by jpober** [comment]
PAPER miriad files can be read in pyuvdata, phased, written out as uvfits, read into FHD, written out as sav files, read into pyuvdata, and unphased, and written out as miriad and the phases are identical at beginning and end.  So no evidence of remaining conjugation issues!

**Comment by bhazelton** [comment]
We are no longer convinced that this has been adequately tested. The code looks like it is doing the wrong thing (i.e. neither miriad nor uvfits uvw directions are swapped). We also do not define the pyuvdata convention, so it is not clear which one should be swapped. We plan to test this with upcoming pyuvsim tests.

**Comment by nkern** [comment]
Relatedly, there is also a error in the pyuvdata documentation on how the baseline integers are created, raised in issue #354
