### ISSUE TITLE
add test for "time" option of uv.phase

### ISSUE THREAD

**Issue by dannyjacobs** [HERA-Team/pyuvdata#53]
the ra was being incorrectly computed for this option. The error went undetected because we do not have  this option covered by a test.  
The solution is to make a phs2src'd file which is phased to the right ascension of the first pointing of the drift scan.

NB: during debugging we discovered that pull_antpols incorrectly sets phase_ra to 0.0 which breaks our assumption that phase_ra being set indicates that the data have been phased.  The strange thing is that the data were already pull_antpoled once in the RTP. so..

**Comment by jpober** [comment]
This is being subsumed by issue #60; we need some sort of phasing testing before this can be accomplished.
