### ISSUE TITLE
Extra fits keywords

### ISSUE THREAD

**Issue by jpober** [HERA-Team/pyuvdata#6]
Need better way to aggregate and recover extra fits keywords in read and then write them out

**Comment by jpober** [comment]
Need to be sure we get extra attributes from before history

**Comment by jpober** [comment]
This is causing an error when trying to run FHD MWA simulations through firstpass, as the delays value set by cotter is not appearing in our uvfits files, and FHD needs the delays to do bandpass calibration.  (Why, exactly, I don't know...).  Unless I'm misunderstanding, I suggest we remove the noncritical flag from this issue.

**Comment by bhazelton** [comment]
FHD needs to know the delay settings in order to figure out the beam. I don't think these are normally passed in the Cotter uvfits -- I think they're normally passed in the metafits, but I can ask Ian

**Comment by bhazelton** [comment]
fixed in latest commit
