### ISSUE TITLE
phasing test

### ISSUE THREAD

**Issue by jpober** [HERA-Team/pyuvdata#60]
With the switch from pyephem ra/dec to a_ra/a_dec (astrometric coordinates), we can no longer unittest our code by comparing with a miriad file phased with aipy.  Perhaps when we get a more generic implementation of phase, we can test with a uvfits file phased using aips or casa?  (We cannot test with uvfits right now, since our phasing code currently only works on drift scanning data.)

**Comment by jpober** [comment]
NB: Be sure to test all phasing methods -- phase to time, phase to ra/dec, and unphase

**Comment by bhazelton** [comment]
The right approach might be to compare to a Cotter phased file.

**Comment by bhazelton** [comment]
this is being addressed under issue #148
