### ISSUE TITLE
Look for non-standard header items and variables in miriad files

### ISSUE THREAD

**Issue by jpober** [HERA-Team/pyuvdata#61]
Currently we only look for specific variables in the miriad header; should accumulate all that are present and add as extra keywords.

**Comment by bhazelton** [comment]
need to add a test that fails on this.

**Comment by bhazelton** [comment]
Non-standard header items (i.e. things that are short and don't change) need to be put into extra_keywords (this we can test for now and will fail). Other useful things might need to be added as optional parameters.

**Comment by bhazelton** [comment]
fixed in PR #214
