### ISSUE TITLE
Clean up unittests

### ISSUE THREAD

**Issue by adampbeardsley** [HERA-Team/pyuvdata#63]
Unittests should be reorganized. They should be set up in a consistent manner (e.g. some define testfile names in setUp function, others do it within specific tests). Should also try to modularize the tests better (only one assertion per test)

**Comment by bhazelton** [comment]
In addition, the tests should be split into different test files following the file structure in the repo, ie test_utils, test_uvfits, test_fhd etc.

**Comment by bhazelton** [comment]
I vote that this should get the version 1.0 milestone tag

**Comment by adampbeardsley** [comment]
I just pushed commit 151d146 on the cleanup_unittests branch. Things are a lot more organized, but could use some more eyes on it before I make an official pull request. There are now several test files to test the corresponding code files. Most of them (except test_uv.py) no longer use the unittest.TestCase subclasses because they didn't actually share much setup/teardown logic. Of course this may change as we add more tests.

**Comment by adampbeardsley** [comment]
Branch has been merged into master.
