### ISSUE TITLE
write_miriad() assigns improper baselines

### ISSUE THREAD

**Issue by jkerrigan** [HERA-Team/pyuvdata#68]
When converting files to miriad format using write_miriad(), the i,j pairs are somehow assigning baselines to the wrong indexes. This issue can be see in two example PAPER64 miriad observation files located on ~/data/shared (on OSCAR), where when using plot_uv.py and looking at the antenna pair 6,33; plot_uv.py tries to plot xx,yy for the 6,33 baseline and xx,yy for the 39,32 baseline.

**Comment by jpober** [comment]
Fixed in latest commit.  Issue was b/c of the miriad conjugation convention.  Some baselines with i > j were being written, which was not allowed.
