### ISSUE TITLE
Dictionary key

### ISSUE THREAD

**Issue by aelanman** [HERA-Team/pyuvdata#69]
The read_fhd method reads a dictionary "flags_dict" from the flags file, and loops over the weights in flags_dict\['flag_arr'\] (line 81). The key in this dictionary is actually "vis_weights" for FHD files that come out of a simulation.
This may be related to a recent commit in FHD that changed variables named "flag" to "weights" or "vis_weights".
I was able to resolve this myself by changing flag_arr to vis_weights, but I don't know if that's sufficient in all cases.

**Comment by bhazelton** [comment]
Fixed in latest commit.
