### ISSUE TITLE
file data mapping stored as dict

### ISSUE THREAD

**Issue by bhazelton** [HERA-Team/pyuvdata#7]
figure out a way to do this properly so both read & write functions use the same dict, different file types use different dicts.

**Comment by dannyjacobs** [comment]
Basically we mean we want one dictionary that defines how each variable maps to each file type. At the moment this is done in each read and write function separately.

ie file_attribute_mapping = {'phase_center_ra':{miriad:'ra','FHD':'obsra','uvfits':'RA',<etc more attributes>}

**Comment by dannyjacobs** [comment]
The conversions are not 1:1 which make it hard for this to work.
