### ISSUE TITLE
fix warnings so they only print the warning message

### ISSUE THREAD

**Issue by bhazelton** [HERA-Team/pyuvdata#78]
don't break warnings tests

**Comment by adampbeardsley** [comment]
This is fixed on commit 5f5a2ac.
Previous, the warning format was:
`file:line_number: category: message`
`<code snippet>`
For example, reading an NRAO uvfits file might result in this warning:
`uvdata/uvfits.py:267: UserWarning: Telescope EVLA is not in known_telescopes.`
`  warnings.warn(str(ve))`
Now only the message is printed:
` Telescope EVLA is not in known_telescopes.`
We may want to add back the file, line number, and category, but that's easy to do if we decide to.
