### ISSUE TITLE
Reading FHD save files with only one time sample

### ISSUE THREAD

**Issue by aelanman** [HERA-Team/pyuvdata#81]
I'm encountering an error with FHD save file that only have one time sample in them.  Line 141 of fhd.py returns an error:
self.time_array[bin_offset[ii]:] = int_times[ii]
IndexError: invalid index to scalar variable.

This may not be a major concern, since most UV data will have more than one integration time in them.

**Comment by bhazelton** [comment]
Ok, I see the problem and I can fix it easily. Can you check that self.Ntimes == 1 for your file?

**Comment by aelanman** [comment]
self.Ntimes == 1 for the uvfits files I give to FHD. The sav files coming out appear to have the correct dimensions, but since the read into pyuvdata doesn't finish the Ntimes isn't set.

**Comment by bhazelton** [comment]
Should be fixed in latest commit.

**Comment by aelanman** [comment]
Thanks!
