### ISSUE TITLE
write_miriad: "expected an int"

### ISSUE THREAD

**Issue by aelanman** [HERA-Team/pyuvdata#86]
The write_miriad method() raises an error in AIPY's miriad writer. To replicate this error, read in a uvfits file to a UVData object, then run write_miriad().

The full trace:

/users/alanman/pyuvdata/uvdata/uvdata.pyc in write_miriad(self, filepath, run_check, run_sanity_check, clobber)
    687         miriad_obj = self._convert_to_filetype('miriad')
    688         miriad_obj.write_miriad(filepath, run_check=True, run_sanity_check=True,
--> 689                                 clobber=clobber)
    690         del(miriad_obj)

/users/alanman/pyuvdata/uvdata/miriad.pyc in write_miriad(self, filepath, run_check, run_sanity_check, clobber)
    358             # NOTE only writing spw 0, not supporting multiple spws for write
    359             for polcnt, pol in enumerate(self.polarization_array):
--> 360                 uv['pol'] = pol
    361                 uv['cnt'] = self.nsample_array[viscnt, 0, :, polcnt].astype(np.double)
    362 

/users/alanman/.local/lib/python2.7/site-packages/aipy/miriad.pyc in **setitem**(self, name, val)
    185         try:
    186             type = self.vartable[name]
--> 187             self._wrvr(name,type,val)
    188         except(KeyError):
    189             self._wrhd(name,val)

ValueError: expected an int

**Comment by adampbeardsley** [comment]
I pushed a change to recast the relevant data to the desired type before writing (commit f87f198f). However, my unittest to check that it works correctly fails for different reasons.

**Comment by adampbeardsley** [comment]
@aelanman Could you please check that this issue is resolved for you? It passes my unit test, but I want to be sure it passes yours before closing.

**Comment by aelanman** [comment]
I just pulled the latest version. No errors when I ran it. This issue appears to be resolved.
