### ISSUE TITLE
miriad_to_uvfits.py not up-to-date

### ISSUE THREAD

**Issue by giannibernardi** [HERA-Team/pyuvdata#91]
miriad_to_uvfits.py does not seem to be up-to-date. If I run it on HERA data I get:

python scripts/miriad_to_uvfits.py ~/HERA/Zaki/firstcal/2457663/zen.2457663.50098.xx.HH.uvcOU
Module dap was already imported from None, but /usr/lib/python2.7/dist-packages is being added to sys.path
Altitude is not present in Miriad file, using known location values for HERA.
Traceback (most recent call last):
  File "scripts/miriad_to_uvfits.py", line 19, in <module>
    UV.phase(time=UV.time_array[0])
TypeError: phase() got an unexpected keyword argument 'time'

I changed that line in my local version according to Jonnie's suggestion and it runs fine now.
Cheers

Gianni

**Comment by dannyjacobs** [comment]
I'd fixed this in my local copy too.  It has now been pushed and is fixed in ef73bac.
