### ISSUE TITLE
read_miriad padding data

### ISSUE THREAD

**Issue by adampbeardsley** [HERA-Team/pyuvdata#92]
This issue is an offshoot of #87. It was discovered that read_miriad assumes Nblts = Ntimes * Nant * (Nant-1)/2. If there are baselines that don't exist, they are padded with zeros. Functionally everything works fine as far as I can tell, but we probably want to remove unnecessary padding.

**Comment by adampbeardsley** [comment]
Note that `test_ReadUVFitsWriteMiriad` fails due to this issue. This was only realized after a bug fix in the __eq__ function of uvbase (see issue #93).

**Comment by bhazelton** [comment]
I'm not sure that this is non-critical if it causes one of our standard tests to fail. I think we need to either fix this issue or the test before version 1.0

**Comment by bhazelton** [comment]
I believe I've fixed this issue. test_ReadUVFitsWriteMiriad is still broken, but not because the array lengths are different. I'm making a new issue for that test (issue #94).
