### ISSUE TITLE
utils.LatLonAlt_from_XYZ fails for telescopes near center of earth

### ISSUE THREAD

**Issue by adampbeardsley** [HERA-Team/pyuvdata#96]
This came up when debugging a faulty uvfits file. The header had both (lat, lon, alt) _and_ xyz defined, but they were both set to (-30.7224, 21.4278, 0.0) -- numbers that would be reasonable for (lat, lon, alt) in degrees. However, pyuvdata prioritizes xyz, and tried using those values to calculate (lat, lon, alt). The result was (180.0, 145.10557405926426, -6378174.4568615155) in degrees. But latitude should be -90 to 90.
My guess is that the datum transformation simply doesn't work at silly values like the center of the earth. So rather than try to fix that calculation, I think we just need to detect this break down and provide the user with a sensible error/warning message.

**Comment by bhazelton** [comment]
An error message is now issued if the telescope location could not be on the surface of the earth.
